### ISSUE TITLE
编辑源文件时提示“请求失败，请刷新页面重试”

### ISSUE THREAD

**Issue by mlosun** [BaoXuebin/beancount-gs#20]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/7459954/177236185-2e187646-0734-4b92-867e-7983d7ffd309.png">
经测试，编辑源文件任意内容都会出现该情况，使用docker安装在群晖服务器上，版本1.1.7，chrome浏览器

**Comment by BaoXuebin** [comment]
能提供一些报错的日志信息吗？

**Comment by quewen08** [comment]
我也发现了，不过找到了问题，环境还是docker下，其他不环境没测。
原因是`/data/beancout/{hash}/bak`目录不存在导致的无法创建备份文件报错。

**Comment by BaoXuebin** [comment]
可能是把 bak 文件夹漏掉了，下个版本加个不存在就创建的逻辑
