### ISSUE TITLE
Docker 中创建的账本没有存在物理机器上，只在docker里有

### ISSUE THREAD

**Issue by quewen08** [BaoXuebin/beancount-gs#21]
如题，请问作者有什么方案吗

**Comment by quewen08** [comment]
通过docker-compose 创建容器，然后在网页上创建账本，能看到日志是输出了create file success，但是在物理机上映射的目录中找不到该文件，只有在docker容器内部才能找到

**Comment by BaoXuebin** [comment]
https://github.com/BaoXuebin/beancount-gs/blob/main/docker-compose.yml
如果不设置参数，账本文件会创建到物理机器的 `/data/beancount` 文件夹。

**Comment by quewen08** [comment]
`
version: "3.9"
services:
  app:
    container_name: beancount-gs
    image: xdbin/beancount-gs:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 10000:80
    # volumes 挂载目录会导 /app/public/icons 中的图标被覆盖，这里将默认图标在挂载后重新拷贝图标    
    # sh -c "cp -rn /app/public/default_icons/* /app/public/icons && ./beancount-gs -p 80"
    command: >
      sh -c "./beancount-gs -p 80"
    volumes:
      - "${dataPath:-/srv/dev-disk-by-uuid-{删掉的hash}/self/data/beancount}:${dataPath:-/data/beancount}"
      - "${dataPath:-/srv/dev-disk-by-uuid-{删掉的hash}/self/data/beancount/public}/icons:/app/public/icons"
      - "${dataPath:-/srv/dev-disk-by-uuid-{删掉的hash}/self/data/beancount}/config:/app/config"
      - "${dataPath:-/srv/dev-disk-by-uuid-{删掉的hash}/self/data/beancount}/bak:/app/bak"
    restart: unless-stopped
`
就这么写的啊

**Comment by quewen08** [comment]
原来如此，明白了。感谢

**Comment by ianzhuo** [comment]
@BaoXuebin ：
作者您好，有關這個帳本存儲位置應寫入`/data/beancount`配置，是不是考慮寫在說明文檔中呢？我在配置docker時也遇到這個問題，還要來這邊翻issue才找到解答，對初用beancount-gs的用戶來說，有點小障礙，謝謝。

**Comment by BaoXuebin** [comment]
不错的建议
