### ISSUE TITLE
🐛 关闭账户之后刷新缓存会发现账户又出来了

### ISSUE THREAD

**Issue by quewen08** [BaoXuebin/beancount-gs#22]
我还在测试环境中试了下，一样的情况

当前环境  `© 2022  
[v1.1.7](https://github.com/BaoXuebin/beancount-gs/releases/tag/v1.1.7) from docker-compose`

**Comment by quewen08** [comment]
![image](https://user-images.githubusercontent.com/16368595/179381722-45fc3c19-6bc9-4dd3-afea-e8afbc3dfe35.png)

发现是文件名称不对，大小写

**Comment by quewen08** [comment]
https://github.com/BaoXuebin/beancount-gs/blob/81738c09d902cbd8307f14efbe3bc970ed1b584c/service/accounts.go#L171

**Comment by quewen08** [comment]
其实还有一个问题，在安装创建账本之后直接修改所有账户(同步其他账户)源文件(文件名全部小写)的情况下，记账不会在任何页面查到，不知道是不是也是和账户文件大小写有关。

**Comment by BaoXuebin** [comment]
是会有这个问题，我开发是在 win10 上，win10 是不区分大小写的，linux 对文件的大小写敏感
