### ISSUE TITLE
共同资产如何记录到自己账户中

### ISSUE THREAD

**Issue by gustinzhang** [BaoXuebin/beancount-gs#26]
请问我和对象共同管理一张借记卡，每个月各自往里面存500，用于共同生活开支。
比如用这个共同账户花费购买20元的外卖。请问这种该如何记录到我的账户资产里呢？

**Comment by BaoXuebin** [comment]
你可以尝试新建一个借记卡的账户，每月总充值1000（自己存入500元，对象以负债的形式存入500元），然后之后的消费记录都从这个账户中扣除。这样可以标记资金来源，也方便生活支出的记录。
```
2022-08-31 open Assets:Card:Life CNY
2022-08-31 open Liabilities:GirlF CNY
2022-08-31 open Assets:Card:AliPay CNY
2022-08-31 open Expenses:Life:Food CNY

2022-09-01 * "转存" "和对象一起各存入500元"
  Assets:Card:AliPay -500.00 CNY
  Liabilities:GirlF -500.00 CNY
  Assets:Card:Life 1000.00 CNY

2022-09-02 * "外卖"
  Assets:Card:Life -20.00 CNY
  Expenses:Life:Food 20.00 CNY
```

**Comment by gustinzhang** [comment]
和你说的一样，创建三个账户：我自己的，对象的，和共同账户。
我的思想是把对象作共同账户的股东，所以在权益账户下创建了个平衡账户，不知道这样是否合理。
![image](https://user-images.githubusercontent.com/56249836/191025712-270de88e-84da-447b-be27-c82dce3a4927.png)

**Comment by BaoXuebin** [comment]
那你记录消费支出是从 SignificantOther 账户扣除吗？

**Comment by gustinzhang** [comment]
是在共同账户里进行扣除，平衡账户记录对象的每笔存款，这样可以吗？
我这种是不是没有搞清平衡账户的概念
不太会把对象存入的资产以负债方式写入和我这种进行区分。

**Comment by BaoXuebin** [comment]
平衡账户一般不会这么使用，但是 beancount 比较灵活，也没用固定的用法。
https://beancount.github.io/docs//the_double_entry_counting_method.html#equity 你可以看看这篇文档。
