### ISSUE TITLE
1.1.9版本页面加载空白

### ISSUE THREAD

**Issue by elliot-yang** [BaoXuebin/beancount-gs#30]
更新1.1.9版本后出现，重新进入账本，页面变成空白，看控制台报错。 

this.state.error.map is not a function

![image](https://user-images.githubusercontent.com/61893460/195968535-5bcf98ca-9926-4feb-bcec-71ae318c0fb0.png)  
 

每次清空localStorage后可重新输入账本密码正常进入，再次刷新就一样的报错了

**Comment by BaoXuebin** [comment]
可以试着 `Ctrl+Shift+R` 清空前端缓存试试

**Comment by elliot-yang** [comment]
> 

一样的， 隐身窗口里也能复现

**Comment by BaoXuebin** [comment]
这好像是个 bug

**Comment by BaoXuebin** [comment]
是一个接口的返回值没判断，在 v1.1.10 修复了
beancount-web: https://github.com/BaoXuebin/beancount-web/commit/c042994ab3b3a05ac21a42767acf800f1194afd4
beancount-gs: https://github.com/BaoXuebin/beancount-gs/commit/0d172a3988ea2a819a251a9e95d6599deaa205db
