### ISSUE TITLE
[FR]：支持记账的API

### ISSUE THREAD

**Issue by windily-cloud** [BaoXuebin/beancount-gs#31]
文档目前有下列API：
● 进入/创建账本：POST/api/ledger
● 月份列表：GET/api/stats/months
● 标签列表：GET/api/tags

如果有记账的API，可以集成到第三方应用中。我想开发一个obsidian的插件，以日记的形式记账（因为我每天不仅需要通过日记记账，还有习惯打卡，日程规划，任务归档之类的），然后通过访问API自动同步到云端beancount中。

或者您有什么其它的建议吗？谢谢你写的beancount-gs，对我的帮助很大！

**Comment by BaoXuebin** [comment]
很高兴能够帮到你，不错的想法，也是我接口化服务的初衷，后续我会在文档上把接口完善下
