### ISSUE TITLE
群晖Docker app文件夹无数据

### ISSUE THREAD

**Issue by zx0922** [BaoXuebin/beancount-gs#35]
用的群晖的Docker，icons和config文件夹正常，/data/beancount对应的文件夹下没有数据

**Comment by BaoXuebin** [comment]
![image](https://user-images.githubusercontent.com/17971651/206961941-045f7cbd-96fc-485f-9a1c-234d38c8b55e.png)
这个位置是写的 /data/beancount 吗？

**Comment by zx0922** [comment]
原来问题在这呀。重新初始化了下，有了。感谢！准备从fava迁移过来
