### ISSUE TITLE
6e860/account/assets.bean:17:      syntax error, unexpected CURRENCY, expecting end of file or EOL

### ISSUE THREAD

**Issue by zx0922** [BaoXuebin/beancount-gs#39]
不管怎么编辑assets.bean文件，都会报这个错，请问:17是17行的错误吗。

重新建立一个账本，只复制assets.bean进去，刷新，不会报错
重新进入了之前报错的账本，没有错误了

**Comment by BaoXuebin** [comment]
这个是新建的账本吗？
17 就是 17行出现 beancount 语法异常
