### ISSUE TITLE
想请问一下有重复记录是怎么处理的呢？

### ISSUE THREAD

**Issue by hkgov** [BaoXuebin/beancount-gs#44]
比如支付宝有一笔从工行卡的支出，导入支付宝账单和工行卡账单后，这笔支出就重复了，逻辑里面有啥处理么？还有就是，演示地址无法访问，白屏了。。

**Comment by BaoXuebin** [comment]
> 比如支付宝有一笔从工行卡的支出，导入支付宝账单和工行卡账单后，这笔支出就重复了，逻辑里面有啥处理么？

这个暂时还没啥好方法，我一般是手动处理。

演示地址已经恢复了 ;-)
