### ISSUE TITLE
docker镜像中缺失图标

### ISSUE THREAD

**Issue by yqchilde** [BaoXuebin/beancount-gs#45]
![image](https://user-images.githubusercontent.com/36953759/215635487-9417be04-ab0a-4640-a1f9-73da21330f27.png)

看起来是这里没成功

`RUN cp -rn /app/public/default_icons/* /app/public/icons`

**Comment by BaoXuebin** [comment]
你是自己打包的 docker 镜像吗？

**Comment by yqchilde** [comment]
用的latest镜像，后来我自己改了下启动方式可以了

```shell
docker run -d \
    --name=beancount \
    ...
    xdbin/beancount-gs:latest \
    sh -c "cp -rn /app/public/default_icons/* /app/public/icons && ./beancount-gs -p 80"
```
