### ISSUE TITLE
windows版本遇到无法保存的问题

### ISSUE THREAD

**Issue by codingbylch** [BaoXuebin/beancount-gs#46]
作者你好，我遇到了在【资产账户】中核算某个账户时，点击刷新或者前进后退，都会让账户变为默认，导致我无法录入数据

刷新前：
![image](https://user-images.githubusercontent.com/17738529/218325441-ce2dc4e2-3e3c-47bb-8dd7-ae9da4071fb3.png)

刷新后：
![image](https://user-images.githubusercontent.com/17738529/218325455-3b2461ef-15f3-4a09-a92d-3fb1f0ab736d.png)

**Comment by BaoXuebin** [comment]
使用的是 v1.1.11 版本吗？

**Comment by codingbylch** [comment]
是的，最新版本1.1.11

**Comment by BaoXuebin** [comment]
这是一个 bug，原因是在初始化账户时没有将新创建的月份文件索引到 `months.bean`

你可以 `编辑源文件`，选择 `month/months.bean` 文件，手动输入 include 内容，如下格式：
```
include "./2023-02.bean"
```

**Comment by codingbylch** [comment]
感谢解答 可以了
