### ISSUE TITLE
账本没法修改密码

### ISSUE THREAD

**Issue by glqynyf** [BaoXuebin/beancount-gs#47]
在新建完账本之后,如果需要修改密码,没有地方进行修改

**Comment by BaoXuebin** [comment]
是的，准确的说这个项目中没有 `密码` 这个概念，账户和密码仅仅是为了区分不同账本的存储位置。

如果有更新密码的需求，可以通过重新设置账户密码的方式，新建一个空账本，然后去账本文件的存储位置（默认是 `/data/beancount`），然后将目标账本中的所有文件复制到新的账本目录下即可。

**Comment by glqynyf** [comment]
好的,再多嘴问下,这样也可以重置密码吧

**Comment by BaoXuebin** [comment]
这样相当于重新复制了一份账本，变相的重置密码
