### ISSUE TITLE
无法修改过去账目

### ISSUE THREAD

**Issue by mikumiku52099** [BaoXuebin/beancount-gs#48]
版本：[v1.1.11](https://github.com/BaoXuebin/beancount-gs/releases/tag/v1.1.11)
问题：1.能否支持相同账目的快捷添加。2.能否添加单项账目的备注。3.能否添加房贷利息的计算模块。

1.您好，我在记账时，有过一个账户多次支出的记录，为此我每次都要进行①点击添加账目②选择账户，这两步操作。请问您能否在已选择的账户的账目旁边添加一个功能键，即”复制当前账户“操作：自动执行添加账目同时选择相同账户？
2.您好，假设我卖出了一件家具，这个交易似乎只能通过”OpeningBalances“来平账，但我想对这一条账目进行备注，请问这一步操作要怎么进行呢？
3.您好，我在记账时，发现当记录还房贷时，涉及到房贷利息，导致从银行卡中扣除的金额会与房贷的扣除不一致。能否请您在房贷这一块添加利息设置，每当进行还款操作时，会自动抵消从银行卡扣除的金额，非常感谢您！

以上是我的问题，非常感谢您能解答！

**Comment by mikumiku52099** [comment]
1.在CLOSE中看到了您以前的回答，还想请问能否将”编辑源数据“的选项用icon+注释标识，找了好久。

**Comment by BaoXuebin** [comment]
1. 这个场景确实存在，不过我觉得太过低频了；选择账户时可以通过模糊搜索，方便快速查找。
2. 卖二手物品这块，我这边的做法是设置了一个专门的收入账户。比如，我这边为卖书设置了 `Income:Other:Book:卖书` 这个收入账户
3. 每期的房贷一般包含本金和利息，我这边的做法是：房贷本金账户视为为负债 `Liabilities:Cycle:ICBC:房贷`，利息视为消费 `Expenses:Finance:HouseLoanFee:房贷利息`，每次都是从银行账户扣钱，到这两个账户。可以保存一个房贷扣除模版，方便记录。

希望能帮到你 :-)
