### ISSUE TITLE
1.1.12版本的docker部署完成之后不能使用

### ISSUE THREAD

**Issue by glqynyf** [BaoXuebin/beancount-gs#50]
按照部署文档部署最新版本的docker之后进入docker之后发现并没有监听80端口的web服务

**Comment by BaoXuebin** [comment]
docker 容器启动的命令能发一下吗

**Comment by glqynyf** [comment]
> docker 容器启动的命令能发一下吗

不好意,问题已经找到了,是启动命令输入错了.
sh -c "cp -rn /app/public/default_icons/* /app/public/icons && ./beancount-gs -p 80"
