### ISSUE TITLE
pad balance是不支持吗

### ISSUE THREAD

**Issue by Lin-Yiheng** [BaoXuebin/beancount-gs#53]
使用pad balance语法后账本就没了，是没支持这个语法吗

**Comment by BaoXuebin** [comment]
这个项目底层是使用 bql 解析 beancount 语法文件，`pad balance` 应该是支持的。可以提供下脱敏数据后的账本文件吗，排查一下问题原因？

**Comment by Lin-Yiheng** [comment]
没看到已经回复了
准备弄下测试数据
就是账本的UI显示是有什么限制么
在已经有Assets:Flow:Bank:BOC:中国银行**** CNY
Assets:Flow:Bank:BOCTEST:中国银行TEST CNY和 Assets:Flow:Bank:BOC:中国银行TEST CNY均不会在现金流账户中显示

**Comment by BaoXuebin** [comment]
账户类型的区分是根据账户的前缀的匹配度定义的，比如：Assets:Flow:Bank:xxx 会自动分类到 Assets:Flow:Bank 中，而不是 Assets:Flow。

你可以编辑源文件，选择 `.beancount-gs/account_type.json` 文件，查看/边界里面的账户类型，若有变更后，点击账户页面的刷新按钮即可同步。
