### ISSUE TITLE
没有显示记录账目

### ISSUE THREAD

**Issue by mikumiku52099** [BaoXuebin/beancount-gs#56]
您好，从7月开始，我记录的账目都没有显示了。源文件上可以查询到，但是在主界面上没有显示，数值为0.

**Comment by mikumiku52099** [comment]
版本为1.1.11

**Comment by mikumiku52099** [comment]
另外我注意到您这边更新了版本，想请问一下，docker端该如何升级呢？

**Comment by BaoXuebin** [comment]
账目不显示，你可以在源文件的 `month/months.bean` 这个文件中查看下是否有7月份的引入，如果缺失，可以进行手动添加。

docker端直接拉取最新的镜像即可，你可以执行 `docker pull xdbin/beancount-gs:latest`
