### ISSUE TITLE
无法支持已有账户类型以外的自定义账户

### ISSUE THREAD

**Issue by KEAE12315** [BaoXuebin/beancount-gs#58]
添加已有账户类型以外的账户时，不能显示出来。
例如，原有的收入账号分为Income:Work，Income:Gov，Income:Gov。一旦建立一个Income:Others，统计和自动补全都会忽略它。这对需要自定义很多账户的人来说非常致命。

**Comment by KEAE12315** [comment]
这部分的定义似乎在template/.beancount-gs/account_type.json里

**Comment by BaoXuebin** [comment]
自定义完成账户类型之后，在账户页面点击刷新缓存，重新加载一下 account_type.json 里面的内容

**Comment by KEAE12315** [comment]
在docker容器中，修改\app\template\.beancount-gs\account_type.jsonwen文件，新增一行"Expenses:Life:Medical": "医疗", 重启container，然后在账户页面刷新，但仍然不能显示新添加的类型。

<img width="295" alt="Snipaste_2023-08-15_09-02-06" src="https://github.com/BaoXuebin/beancount-gs/assets/61793130/3c2a33f0-10b9-4c4d-bce4-ae6947a929b2">
<img width="92" alt="Snipaste_2023-08-15_09-15-23" src="https://github.com/BaoXuebin/beancount-gs/assets/61793130/262b6c3f-37d1-4158-8628-209c7a758931">

**Comment by BaoXuebin** [comment]
如果一个类型下面没有关联账户，是不会显示的。你可以新加个账户试试

**Comment by KEAE12315** [comment]
当时没有放那个图，实际上已经新加了账户，也没有显示
![image](https://github.com/BaoXuebin/beancount-gs/assets/61793130/76da24c5-450a-4120-9d12-081600332d89)

**Comment by BaoXuebin** [comment]
> 这部分的定义似乎在template/.beancount-gs/account_type.json里

没注意这里，`template` 是模版文件夹，里面的内容是生成新账本用的，改动这个对你既有的账本是无效的。

在 `账户` 页面点击 `编辑源文件` 按钮，修改 `.beancount-gs/account_type.json` 和 `account/expenses.bean` 这两个文件内容再点击刷新即可。

**Comment by BaoXuebin** [comment]
关于账户的操作，你可以看看这个文档：https://github.com/BaoXuebin/beancount-gs/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B4%A6%E6%88%B7

**Comment by KEAE12315** [comment]
在源文件中的修改已经生效，感谢您的建议。以及，在仔细查看文档之后我发现这个功能已经在新增账户分类里了。也许可以考虑更显著一些的方式。再次感谢！
