### ISSUE TITLE
关于资产负债统计按年统计显示不正确问题

### ISSUE THREAD

**Issue by glqynyf** [BaoXuebin/beancount-gs#60]
使用版本为1.1.13版本,在查看资产统计选择年度统计时只显示当前月的统计,选择所有显示正常.问题如图
![image](https://github.com/BaoXuebin/beancount-gs/assets/60341617/68d046ef-d9c0-4250-bb4c-eb77e7e797ea)
![1697342848783](https://github.com/BaoXuebin/beancount-gs/assets/60341617/6278e25a-3325-4d22-80b4-9d80a439629e)

**Comment by BaoXuebin** [comment]
你好，我这边未能复现出这个问题，你可以 `Ctrl+Shift+R` 刷新下浏览器缓存试试。

也可以查看下图的请求参数是否正确，

![image](https://github.com/BaoXuebin/beancount-gs/assets/17971651/cfbbcaa9-9f48-4fef-b8cd-365ed4e05d2b)

**Comment by glqynyf** [comment]
后来我又试了几遍,发现,只有safari浏览器是这样,mac端和IOS
端都是,其他的浏览器都是正常的

**Comment by BaoXuebin** [comment]
最新的 v1.1.14 版本已经修复了这个问题，可以更新试试看

**Comment by glqynyf** [comment]
> 最新的v1.1.14 版本已经修复了这个问题，可以更新试试看

好的,感谢大神
