### ISSUE TITLE
跨币种时，模版中汇率无法回显

### ISSUE THREAD

**Issue by chenguixu2233** [BaoXuebin/beancount-gs#65]
![微信图片_20231223124312](https://github.com/BaoXuebin/beancount-gs/assets/71803094/4b154deb-ece6-43b7-b3c5-9b5d2811620b)

**Comment by BaoXuebin** [comment]
需要将对应 货币 添加到 currency.json 文件中，格式类似：

```json
{"name":"三顿半","currency":"SATURN_BIRD","symbol":"SATURN_BIRD"}
```

如下图
![微信截图_20231225161759](https://github.com/BaoXuebin/beancount-gs/assets/17971651/5dcc7ae6-b484-492c-a220-fb126696b73e)

添加完成后，点击账户页面的 刷新 按钮即可。

https://www.yuque.com/chuyi-ble7p/beancount-gs/wxwcdgv881z0wmgc

**Comment by chenguixu2233** [comment]
感谢
