### ISSUE TITLE
跨币种时的记账在fava上的显示

### ISSUE THREAD

**Issue by chenguixu2233** [BaoXuebin/beancount-gs#66]
```beancount
2024-01-30 * "三顿半" "咖啡"
 Assets:Fixed:三顿半咖啡 -1.00 SATURN_BIRD
 Expenses:Life:Food:Coffee:咖啡 5.61 CNY
 Equity:OpeningBalances
```
如果不加` {} @ 5.61 CNY`，存在币种转换的显示异常
![1706608516596](https://github.com/BaoXuebin/beancount-gs/assets/71803094/f35bee05-414c-402e-999a-a70a43d33edb)

**Comment by BaoXuebin** [comment]
感谢指出，目前的实现有问题，只能通过添加 `Equity:OpeningBalances` 来强制平衡账目。

下个版本考虑改成下面的格式：

```
2024-01-30 * "三顿半" "咖啡"
 Assets:Fixed:三顿半咖啡 -1.00 SATURN_BIRD {5.61 CNY}
 Expenses:Life:Food:Coffee:咖啡 5.61 CNY
```

**Comment by chenguixu2233** [comment]
感谢，感觉`Equity:OpeningBalances`对单笔记账平衡有害，去掉挺好
