### ISSUE TITLE
docker部署后怎么获取密钥

### ISSUE THREAD

**Issue by 18611429192** [BaoXuebin/beancount-gs#67]
如题
我使用docker进行部署后，没有办法获取密钥，无法进行初始化。
`docker attach 容器ID`只能看到一些get、post的日志，看不到密钥日志
`docker exec -it 容器ID bash`也进不去

**Comment by BaoXuebin** [comment]
docker 容器重启后，可以使用 `docker logs` 查看日志。

可以参考这个：

https://www.yuque.com/chuyi-ble7p/beancount-gs/eq81d8

**Comment by 18611429192** [comment]
好的，谢谢

**Comment by DosLee** [comment]
`docker logs` 接容器ID或容器名称网上翻
