### ISSUE TITLE
不用的示例账簿可以添加一个删除按钮吗？ 新建账簿时请添加判定是否为空密码账簿

### ISSUE THREAD

**Issue by RenLangMan** [BaoXuebin/beancount-gs#7]
我使用docker方式部署[dockhub](https://hub.docker.com/layers/xdbin/beancount-gs/latest/images/sha256-5934a88b55bfba8c89b6163985a654e3691f7ea8f308f153b0de1cad18391ab2?context=explore)上的V1.1.3版本到腾讯云服务器，

我是单服务器ip地址 跑多个网站/服务，
为什么只能使用服务器ip地址+端口号10000访问此界面，不能使用域名beancount.XXXX.com访问docker容器中的这个网页？

另外我新建了多个账套，如果某个账套不需要显示在首页可以增加一个删除此账簿的按钮吗

为什么我初始化账簿时候，账簿空白密码也可以初始化成功，这是不安全的 希望能拒绝空密码初始化账簿

添加删除账簿功能 删除掉这个空密码的账簿

**Comment by BaoXuebin** [comment]
> 我是单服务器ip地址 跑多个网站/服务，为什么只能使用服务器ip地址+端口号10000访问此界面，不能使用域名beancount.XXXX.com访问docker容器中的这个网页？

这个应该是你域名解析的配置有问题，你可以检查下二级域名的解析配置。

**Comment by BaoXuebin** [comment]
关于是否必须需要密码的情况，因为有的场景是局域网使用，密码显得有点多余；当然在支持公网访问时，鉴于安全性，密码是必须的。下个版本会优化不设置密码时的风险提示。

删除账本这个功能在开发计划中，下个版本提供。如果你现在需要隐藏没有密码的账本，可以到服务器的数据目录（默认/da ta/beancount）自行修改 ledger_config.json 这个文件，删除对应的账本数据，然后重启 docker 容器。

**Comment by BaoXuebin** [comment]
v1.1.4更新了账本删除：https://www.yuque.com/chuyi-ble7p/beancount-gs/qbbm4a#z8tvZ
