### ISSUE TITLE
多币种转换时小数点后金额无法计算导致报错

### ISSUE THREAD

**Issue by mikumiku52099** [BaoXuebin/beancount-gs#77]
版本:[v1.1.15]
问题内容:当我进行购汇记账的时候，按照实际出入金额录入时，不会出现小数点后4位的情况，但系统计算时会考虑到小数点后4位，导致账目不平衡报错。但同时也可以保存账目。
![1](https://github.com/BaoXuebin/beancount-gs/assets/37678832/a6927a9c-76d3-4c6a-a3a5-2ece57174887)
![3](https://github.com/BaoXuebin/beancount-gs/assets/37678832/31aee988-6da7-4ae4-ac57-7b6da643fad9)
请问该如何操作才能消除账目不平衡问题？

**Comment by mikumiku52099** [comment]
> 版本:[v1.1.15] 问题内容:当我进行购汇记账的时候，按照实际出入金额录入时，不会出现小数点后4位的情况，但系统计算时会考虑到小数点后4位，导致账目不平衡报错。但同时也可以保存账目。 ![1](https://private-user-images.githubusercontent.com/37678832/333775444-a6927a9c-76d3-4c6a-a3a5-2ece57174887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTYzNDMsIm5iZiI6MTcxNjYxNjA0MywicGF0aCI6Ii8zNzY3ODgzMi8zMzM3NzU0NDQtYTY5MjdhOWMtNzZkMy00YzZhLWEzYTUtMmVjZTU3MTc0ODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA1NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Mzk0N2VjNDg4NWJjOGIxODY0OWI0YjgwNjFkYTRjY2Y4MWI1ZDY0YmY5ODgxYjMxZjVkODFkMDUxOWVmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.27bkY6rKbpFfCZhCrmC3Ao0oTFkW6teGw6ri5HALYA8) ![3](https://private-user-images.githubusercontent.com/37678832/333775448-31aee988-6da7-4ae4-ac57-7b6da643fad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTYzNDMsIm5iZiI6MTcxNjYxNjA0MywicGF0aCI6Ii8zNzY3ODgzMi8zMzM3NzU0NDgtMzFhZWU5ODgtNmRhNy00YWU0LWFjNTctN2I2ZGE2NDNmYWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA1NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDlhMTMwMmIyMGU2N2I2NmE2NWY5ZTZhZGZmNjgxMTI1NmQ5ZTZmMGU1ZWEzY2I5NDdmOTZkOWYzN2ZjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oq9aZKRV-VyssM6rwzjmL9FM7YtvTD2jerHyJXEsKaU) 请问该如何操作才能消除账目不平衡问题？

**Comment by BaoXuebin** [comment]
我个人做法一般是提高汇率精度，这里讲7.24 -> 7.2449 就不会出现错误了，一般我是保留4位小数。beancount默认精度为0.01，将误差值保留至0.01以下就不会出现错误提示。

当然也可以选择无视，当误差累计后定时进行消除即可。
![image](https://github.com/BaoXuebin/beancount-gs/assets/17971651/449b483e-b813-42a1-943c-7bf78154e778)
