### ISSUE TITLE
带汇率的账户转出不生效

### ISSUE THREAD

**Issue by glqynyf** [BaoXuebin/beancount-gs#79]
如图所示,转出账户为带汇率的账户,转入账户为不带汇率的账户.源文件有相关信息,但两个账户的金额还是之前的金额
![WechatIMG25](https://github.com/BaoXuebin/beancount-gs/assets/60341617/b4fc4586-58d0-454f-badd-056e579edb5e)

**Comment by BaoXuebin** [comment]
你的账户货币单位好像有问题，你换成 大写 ZYKJCX 试试。

参考：https://beancount.github.io/docs//beancount_language_syntax.html#commodities-currencies
![5d3426c97e9929ff966a434802dac3e](https://github.com/BaoXuebin/beancount-gs/assets/17971651/0bb32b44-2006-46c1-8322-8ec10077f177)

**Comment by glqynyf** [comment]
果然是大小写的问题，全部改成大写好了
