### ISSUE TITLE
feat: 是否新增邮件定时轮训导入支付宝账单或者其他第三方账单

### ISSUE THREAD

**Issue by Gmakter** [BaoXuebin/beancount-gs#83]
是否在程序中新增邮件接收功能来自动读取订阅的第三方账单

**Comment by BaoXuebin** [comment]
有单独开发能力，可以另开发一个 邮件定时轮询 的服务，然后调用 beancount-gs 的接口去新增账单。这个项目暂不考虑去实现这个 feat
