### ISSUE TITLE
求安装教程

### ISSUE THREAD

**Issue by GaoKaiNing** [BaoXuebin/beancount-gs#88]

**Comment by GaoKaiNing** [comment]
我已经安装了beancount，为啥还是检测未安装啊

**Comment by BaoXuebin** [comment]
你可以在电脑命令行执行 `bean-query --version`，如果可以正常输出版本信息，就会检测通过。

否则，可以检查 beancount 是否配置到了 path 路径。

https://www.yuque.com/chuyi-ble7p/beancount-gs/eq81d8
