### ISSUE TITLE
请问 核算账户是什么意思，怎么一使用，右上角就有红色提醒

### ISSUE THREAD

**Issue by GE-fighting** [BaoXuebin/beancount-gs#91]

**Comment by BaoXuebin** [comment]
核算账户就是 balance 对账的意思，beancount会忽略这个账户在指定日期前的所有交易情况，按指定的账户金额重新开始。
这里会使用pad和balance对账户进行处理。详细你可以参考：官方文档https://beancount.github.io/docs//beancount_language_syntax.html#pad

右上角有红色提醒是说明账本存在beancount语法错误，这个要具体情况具体分析，如果目前不影响使用，我习惯是直接忽略。

**Comment by GE-fighting** [comment]
> 核算账户就是 balance 对账的意思，beancount会忽略这个账户在指定日期前的所有交易情况，按指定的账户金额重新开始。 这里会使用pad和balance对账户进行处理。详细你可以参考：官方文档https://beancount.github.io/docs//beancount_language_syntax.html#pad
> 
> 右上角有红色提醒是说明账本存在beancount语法错误，这个要具体情况具体分析，如果目前不影响使用，我习惯是直接忽略。

好的，谢谢大佬
